// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireit

import (
	"github.com/ForeverSRC/golang-dev-manual/gdm/internal/adapter/filesystem"
	"github.com/ForeverSRC/golang-dev-manual/gdm/internal/api/clihandler"
	"github.com/ForeverSRC/golang-dev-manual/gdm/internal/ittest"
	"github.com/ForeverSRC/golang-dev-manual/gdm/internal/repository/jsonfile"
	"github.com/ForeverSRC/golang-dev-manual/gdm/internal/service"
)

// Injectors from di.go:

// InitializeCLIITTestContainer injects gdm-cli's integration-test dependencies with wire over the fixture data tree.
func InitializeCLIITTestContainer() (*CLIITTestContainer, error) {
	fs, err := ittest.ITProvideDataTree()
	if err != nil {
		return nil, err
	}
	repository := jsonfile.New(fs)
	scanner := filesystem.NewScanner()
	manualService := service.NewManualService(repository, repository, scanner)
	writer := filesystem.NewWriter()
	generator := service.NewGenerator(repository, repository, writer)
	commandLineHandler := clihandler.New(manualService, generator)
	cliitTestContainer := &CLIITTestContainer{
		Handler: commandLineHandler,
	}
	return cliitTestContainer, nil
}
