// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/ForeverSRC/golang-dev-manual/gdm/data"
	"github.com/ForeverSRC/golang-dev-manual/gdm/internal/adapter/filesystem"
	"github.com/ForeverSRC/golang-dev-manual/gdm/internal/api/clihandler"
	"github.com/ForeverSRC/golang-dev-manual/gdm/internal/repository/jsonfile"
	"github.com/ForeverSRC/golang-dev-manual/gdm/internal/server"
	"github.com/ForeverSRC/golang-dev-manual/gdm/internal/service"
)

// Injectors from di.go:

// InitializeGenerator injects gdm-gen's dependencies with wire.
func InitializeGenerator() (*GeneratorContainer, error) {
	fs := _wireFSValue
	repository := jsonfile.New(fs)
	scanner := filesystem.NewScanner()
	manualService := service.NewManualService(repository, repository, scanner)
	writer := filesystem.NewWriter()
	generator := service.NewGenerator(repository, repository, writer)
	commandLineHandler := clihandler.New(manualService, generator)
	generatorCommand := server.ProvideGeneratorCommand(commandLineHandler)
	generatorContainer := &GeneratorContainer{
		RootCmd: generatorCommand,
	}
	return generatorContainer, nil
}

var (
	_wireFSValue = data.FS
)
